// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_ENCRYPTEDMESSAGE_CANARYLIB_H_
#define FLATBUFFERS_GENERATED_ENCRYPTEDMESSAGE_CANARYLIB_H_

#include "flatbuffers/flatbuffers.h"

#include "header_generated.h"

namespace CanaryLib {

struct EncryptedMessage;
struct EncryptedMessageBuilder;

struct EncryptedMessage FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef EncryptedMessageBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_HEADER = 4,
    VT_BODY = 6
  };
  const CanaryLib::Header *header() const {
    return GetPointer<const CanaryLib::Header *>(VT_HEADER);
  }
  const flatbuffers::Vector<uint8_t> *body() const {
    return GetPointer<const flatbuffers::Vector<uint8_t> *>(VT_BODY);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_HEADER) &&
           verifier.VerifyTable(header()) &&
           VerifyOffset(verifier, VT_BODY) &&
           verifier.VerifyVector(body()) &&
           verifier.EndTable();
  }
};

struct EncryptedMessageBuilder {
  typedef EncryptedMessage Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_header(flatbuffers::Offset<CanaryLib::Header> header) {
    fbb_.AddOffset(EncryptedMessage::VT_HEADER, header);
  }
  void add_body(flatbuffers::Offset<flatbuffers::Vector<uint8_t>> body) {
    fbb_.AddOffset(EncryptedMessage::VT_BODY, body);
  }
  explicit EncryptedMessageBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<EncryptedMessage> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<EncryptedMessage>(end);
    return o;
  }
};

inline flatbuffers::Offset<EncryptedMessage> CreateEncryptedMessage(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<CanaryLib::Header> header = 0,
    flatbuffers::Offset<flatbuffers::Vector<uint8_t>> body = 0) {
  EncryptedMessageBuilder builder_(_fbb);
  builder_.add_body(body);
  builder_.add_header(header);
  return builder_.Finish();
}

inline flatbuffers::Offset<EncryptedMessage> CreateEncryptedMessageDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<CanaryLib::Header> header = 0,
    const std::vector<uint8_t> *body = nullptr) {
  auto body__ = body ? _fbb.CreateVector<uint8_t>(*body) : 0;
  return CanaryLib::CreateEncryptedMessage(
      _fbb,
      header,
      body__);
}

inline const CanaryLib::EncryptedMessage *GetEncryptedMessage(const void *buf) {
  return flatbuffers::GetRoot<CanaryLib::EncryptedMessage>(buf);
}

inline const CanaryLib::EncryptedMessage *GetSizePrefixedEncryptedMessage(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<CanaryLib::EncryptedMessage>(buf);
}

inline bool VerifyEncryptedMessageBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<CanaryLib::EncryptedMessage>(nullptr);
}

inline bool VerifySizePrefixedEncryptedMessageBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<CanaryLib::EncryptedMessage>(nullptr);
}

inline void FinishEncryptedMessageBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<CanaryLib::EncryptedMessage> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedEncryptedMessageBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<CanaryLib::EncryptedMessage> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace CanaryLib

#endif  // FLATBUFFERS_GENERATED_ENCRYPTEDMESSAGE_CANARYLIB_H_
