// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_GENERALSTRUCTURES_CANARYLIB_H_
#define FLATBUFFERS_GENERATED_GENERALSTRUCTURES_CANARYLIB_H_

#include "flatbuffers/flatbuffers.h"

namespace CanaryLib {

struct Light;

struct Position;

struct Outfit;

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(1) Light FLATBUFFERS_FINAL_CLASS {
 private:
  uint8_t color_;
  uint8_t intensity_;

 public:
  Light()
      : color_(0),
        intensity_(0) {
  }
  Light(uint8_t _color, uint8_t _intensity)
      : color_(flatbuffers::EndianScalar(_color)),
        intensity_(flatbuffers::EndianScalar(_intensity)) {
  }
  uint8_t color() const {
    return flatbuffers::EndianScalar(color_);
  }
  uint8_t intensity() const {
    return flatbuffers::EndianScalar(intensity_);
  }
};
FLATBUFFERS_STRUCT_END(Light, 2);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(2) Position FLATBUFFERS_FINAL_CLASS {
 private:
  uint16_t x_;
  uint16_t y_;
  uint8_t z_;
  int8_t padding0__;

 public:
  Position()
      : x_(0),
        y_(0),
        z_(0),
        padding0__(0) {
    (void)padding0__;
  }
  Position(uint16_t _x, uint16_t _y, uint8_t _z)
      : x_(flatbuffers::EndianScalar(_x)),
        y_(flatbuffers::EndianScalar(_y)),
        z_(flatbuffers::EndianScalar(_z)),
        padding0__(0) {
  }
  uint16_t x() const {
    return flatbuffers::EndianScalar(x_);
  }
  uint16_t y() const {
    return flatbuffers::EndianScalar(y_);
  }
  uint8_t z() const {
    return flatbuffers::EndianScalar(z_);
  }
};
FLATBUFFERS_STRUCT_END(Position, 6);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(2) Outfit FLATBUFFERS_FINAL_CLASS {
 private:
  uint16_t id_;
  uint8_t body_;
  uint8_t feet_;
  uint8_t head_;
  uint8_t legs_;
  uint8_t addon_;
  int8_t padding0__;
  uint16_t mount_;
  uint16_t item_id_;

 public:
  Outfit()
      : id_(0),
        body_(0),
        feet_(0),
        head_(0),
        legs_(0),
        addon_(0),
        padding0__(0),
        mount_(0),
        item_id_(0) {
    (void)padding0__;
  }
  Outfit(uint16_t _id, uint8_t _body, uint8_t _feet, uint8_t _head, uint8_t _legs, uint8_t _addon, uint16_t _mount, uint16_t _item_id)
      : id_(flatbuffers::EndianScalar(_id)),
        body_(flatbuffers::EndianScalar(_body)),
        feet_(flatbuffers::EndianScalar(_feet)),
        head_(flatbuffers::EndianScalar(_head)),
        legs_(flatbuffers::EndianScalar(_legs)),
        addon_(flatbuffers::EndianScalar(_addon)),
        padding0__(0),
        mount_(flatbuffers::EndianScalar(_mount)),
        item_id_(flatbuffers::EndianScalar(_item_id)) {
  }
  uint16_t id() const {
    return flatbuffers::EndianScalar(id_);
  }
  uint8_t body() const {
    return flatbuffers::EndianScalar(body_);
  }
  uint8_t feet() const {
    return flatbuffers::EndianScalar(feet_);
  }
  uint8_t head() const {
    return flatbuffers::EndianScalar(head_);
  }
  uint8_t legs() const {
    return flatbuffers::EndianScalar(legs_);
  }
  uint8_t addon() const {
    return flatbuffers::EndianScalar(addon_);
  }
  uint16_t mount() const {
    return flatbuffers::EndianScalar(mount_);
  }
  uint16_t item_id() const {
    return flatbuffers::EndianScalar(item_id_);
  }
};
FLATBUFFERS_STRUCT_END(Outfit, 12);

}  // namespace CanaryLib

#endif  // FLATBUFFERS_GENERATED_GENERALSTRUCTURES_CANARYLIB_H_
