// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_ITEMDATA_CANARYLIB_H_
#define FLATBUFFERS_GENERATED_ITEMDATA_CANARYLIB_H_

#include "flatbuffers/flatbuffers.h"

#include "creature_data_generated.h"
#include "general_structures_generated.h"

namespace CanaryLib {

struct ItemData;

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(2) ItemData FLATBUFFERS_FINAL_CLASS {
 private:
  uint16_t id_;
  uint16_t count_;
  uint16_t fluid_type_;

 public:
  ItemData()
      : id_(0),
        count_(0),
        fluid_type_(0) {
  }
  ItemData(uint16_t _id, uint16_t _count, uint16_t _fluid_type)
      : id_(flatbuffers::EndianScalar(_id)),
        count_(flatbuffers::EndianScalar(_count)),
        fluid_type_(flatbuffers::EndianScalar(_fluid_type)) {
  }
  uint16_t id() const {
    return flatbuffers::EndianScalar(id_);
  }
  uint16_t count() const {
    return flatbuffers::EndianScalar(count_);
  }
  uint16_t fluid_type() const {
    return flatbuffers::EndianScalar(fluid_type_);
  }
};
FLATBUFFERS_STRUCT_END(ItemData, 6);

}  // namespace CanaryLib

#endif  // FLATBUFFERS_GENERATED_ITEMDATA_CANARYLIB_H_
