// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_LOGININFO_CANARYLIB_H_
#define FLATBUFFERS_GENERATED_LOGININFO_CANARYLIB_H_

#include "flatbuffers/flatbuffers.h"

namespace CanaryLib {

struct LoginInfo;
struct LoginInfoBuilder;

struct LoginInfo FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef LoginInfoBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ACCOUNT = 4,
    VT_AUTH_TOKEN = 6,
    VT_PASSWORD = 8,
    VT_XTEA_KEY = 10
  };
  const flatbuffers::String *account() const {
    return GetPointer<const flatbuffers::String *>(VT_ACCOUNT);
  }
  const flatbuffers::String *auth_token() const {
    return GetPointer<const flatbuffers::String *>(VT_AUTH_TOKEN);
  }
  const flatbuffers::String *password() const {
    return GetPointer<const flatbuffers::String *>(VT_PASSWORD);
  }
  const flatbuffers::Vector<uint32_t> *xtea_key() const {
    return GetPointer<const flatbuffers::Vector<uint32_t> *>(VT_XTEA_KEY);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ACCOUNT) &&
           verifier.VerifyString(account()) &&
           VerifyOffset(verifier, VT_AUTH_TOKEN) &&
           verifier.VerifyString(auth_token()) &&
           VerifyOffset(verifier, VT_PASSWORD) &&
           verifier.VerifyString(password()) &&
           VerifyOffset(verifier, VT_XTEA_KEY) &&
           verifier.VerifyVector(xtea_key()) &&
           verifier.EndTable();
  }
};

struct LoginInfoBuilder {
  typedef LoginInfo Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_account(flatbuffers::Offset<flatbuffers::String> account) {
    fbb_.AddOffset(LoginInfo::VT_ACCOUNT, account);
  }
  void add_auth_token(flatbuffers::Offset<flatbuffers::String> auth_token) {
    fbb_.AddOffset(LoginInfo::VT_AUTH_TOKEN, auth_token);
  }
  void add_password(flatbuffers::Offset<flatbuffers::String> password) {
    fbb_.AddOffset(LoginInfo::VT_PASSWORD, password);
  }
  void add_xtea_key(flatbuffers::Offset<flatbuffers::Vector<uint32_t>> xtea_key) {
    fbb_.AddOffset(LoginInfo::VT_XTEA_KEY, xtea_key);
  }
  explicit LoginInfoBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<LoginInfo> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<LoginInfo>(end);
    return o;
  }
};

inline flatbuffers::Offset<LoginInfo> CreateLoginInfo(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::String> account = 0,
    flatbuffers::Offset<flatbuffers::String> auth_token = 0,
    flatbuffers::Offset<flatbuffers::String> password = 0,
    flatbuffers::Offset<flatbuffers::Vector<uint32_t>> xtea_key = 0) {
  LoginInfoBuilder builder_(_fbb);
  builder_.add_xtea_key(xtea_key);
  builder_.add_password(password);
  builder_.add_auth_token(auth_token);
  builder_.add_account(account);
  return builder_.Finish();
}

inline flatbuffers::Offset<LoginInfo> CreateLoginInfoDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const char *account = nullptr,
    const char *auth_token = nullptr,
    const char *password = nullptr,
    const std::vector<uint32_t> *xtea_key = nullptr) {
  auto account__ = account ? _fbb.CreateString(account) : 0;
  auto auth_token__ = auth_token ? _fbb.CreateString(auth_token) : 0;
  auto password__ = password ? _fbb.CreateString(password) : 0;
  auto xtea_key__ = xtea_key ? _fbb.CreateVector<uint32_t>(*xtea_key) : 0;
  return CanaryLib::CreateLoginInfo(
      _fbb,
      account__,
      auth_token__,
      password__,
      xtea_key__);
}

inline const CanaryLib::LoginInfo *GetLoginInfo(const void *buf) {
  return flatbuffers::GetRoot<CanaryLib::LoginInfo>(buf);
}

inline const CanaryLib::LoginInfo *GetSizePrefixedLoginInfo(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<CanaryLib::LoginInfo>(buf);
}

inline bool VerifyLoginInfoBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<CanaryLib::LoginInfo>(nullptr);
}

inline bool VerifySizePrefixedLoginInfoBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<CanaryLib::LoginInfo>(nullptr);
}

inline void FinishLoginInfoBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<CanaryLib::LoginInfo> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedLoginInfoBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<CanaryLib::LoginInfo> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace CanaryLib

#endif  // FLATBUFFERS_GENERATED_LOGININFO_CANARYLIB_H_
